name: Build and publish new release on version tag
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get clean tag name
        id: clean_tag
        run: echo "tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')" >> $GITHUB_OUTPUT
      - name: Create GH-Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./body-file.txt
          fail_on_unmatched_files: true

  build:
    needs: make-release
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get clean tag name
        id: clean_tag
        run: echo "tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')" >> $GITHUB_OUTPUT
      - name: Get exe name
        id: exe_name
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "name=gpth-linux" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "name=gpth-windoza.exe" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "name=gpth-macos" >> $GITHUB_OUTPUT
          else
            echo "Unknown OS: $RUNNER_OS"
            exit 69
          fi
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Build exe
        run: dart compile exe bin/gpth.dart -o ./${{ steps.exe_name.outputs.name }}
      - name: Add files to GH-Release
        uses: softprops/action-gh-release@v1
        with:
          # this supports globs :>
          files: ./gpth-*
          fail_on_unmatched_files: true

